#!/bin/bash
#
# Copyright (c) 2013-2014, SeeCare.CVTE
# All rights reserved.
#
##############################################
# Author	: QiuWeibo
# Version	: V1.0.0
# Date		: 2014-6-25
# Comment	: script for make uboot for aio-bf512
##############################################

# Method 1:
./MAKEALL bf518f-ezbrd

# Method 2:
#make distclean
#make bf518f-ezbrd_config
#make all

