/*********************************************************************************

Copyright(c) 2004-2010 Analog Devices, Inc. All Rights Reserved.

This software is proprietary and confidential.  By using this software you agree
to the terms of the associated Analog Devices License Agreement.

$Revision: 2504 $
$Date: 2010-04-12 16:13:57 -0400 (Mon, 12 Apr 2010) $

Description:
            This file pulls in the proper RTOS API

*********************************************************************************/

#ifndef __ADI_RTOS_H__
#define __ADI_RTOS_H__

/********************************************************************************/

/*******************************************************************************

    Standalone definitions

********************************************************************************/

/* nothing needs done for standalone */
#if defined(ADI_SSL_STANDALONE)
#endif




/*******************************************************************************

    VDK definitions

    Note that the contents of this file are automatically generated by 
    the VDK wizard (this file is basically vdk.h with the addition of the 
    kDoNotWait macro as this does not seem to be defined in vdk.h and the 
    commenting out of the line "#include <cdefbf533.h>").  When the user 
    creates his/her application, the actual vdk.h file that he/she 
    creates will be different than the contents of this file.  Though 
    perhaps worrisome, it doesn't really matter because we're only pulling
    the API from this file, nothing more.  
    
********************************************************************************/

#if defined(ADI_SSL_VDK)
/************ additionally defined in excess of vdk.h *************/
#ifndef kDoNotWait
#define kDoNotWait (UINT_MAX)
#endif
#include "vdk.h"
#endif



/*******************************************************************************

    uC/OS-II definitions
    
    The uC/OS-II definitions are the exact include files from uC/OS-II

********************************************************************************/

#if defined(ADI_SSL_UCOS)
#include "ucos_ii.h"
#include "os_cpu.h"
#endif



/*******************************************************************************

    ThreadX definitions

********************************************************************************/

#if defined(ADI_SSL_THREADX)
#endif


/*******************************************************************************

    Velocity definitions

********************************************************************************/

#if defined(ADI_SSL_INTEGRITY)
#endif




/********************************************************************************/


#endif  // __ADI_RTOS_H__
